### ISSUE TITLE
NoClassDefFoundError when packing on OmegaT 5.7.2-capstan

### ISSUE THREAD

**Issue by msoutopico** [briacp/plugin-omt-package#13]
### Preconditions

Version: OmegaT-5.7.2_0_a9414daaa
Platform: Linux 6.1.38-2-lts
Java: 11.0.19 amd64
Memory: 904MiB total / 848MiB free / 12006MiB max

Plugin version: plugin-omt-package-1.8.0.jar

### Steps

1. `./gradlew run`
2. Open team project
3. Pack the project

### Results

The following error: 

![](https://imgur.com/4A7i1Fv.png)

In the terminal:

``` 
93932: Info: Project saving end (LOG_DATAENGINE_SAVE_END)
93932: Info: Event: project change - "SAVE" (LOG_INFO_EVENT_PROJECT_CHANGE)
93932: Error: Unable to read project file!  (PP_ERROR_UNABLE_TO_READ_PROJECT_FILE)
93932: Error: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils 
93932: Error:   at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) 
93932: Error:   at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191) 
93932: Error:   at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613) 
93932: Error:   at net.briac.omegat.plugin.omt.ManageOMTPackage$3.done(ManageOMTPackage.java:476) 
93932: Error:   at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750) 
93932: Error:   at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:847) 
93932: Error:   at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112) 
93932: Error:   at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:857) 
93932: Error:   at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317) 
93932: Error:   at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249) 
93932: Error:   at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) 
93932: Error:   at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) 
93932: Error:   at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) 
93932: Error:   at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715) 
93932: Error:   at java.base/java.security.AccessController.doPrivileged(Native Method) 
93932: Error:   at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) 
93932: Error:   at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740) 
93932: Error:   at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) 
93932: Error:   at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) 
93932: Error:   at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) 
93932: Error:   at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) 
93932: Error:   at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) 
93932: Error:   at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90) 
93932: Error: Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils 
93932: Error:   at net.briac.omegat.plugin.omt.ProjectFileStorage.getPathForStoring(ProjectFileStorage.java:131) 
93932: Error:   at net.briac.omegat.plugin.omt.ProjectFileStorage.writeProjectFile(ProjectFileStorage.java:90) 
93932: Error:   at net.briac.omegat.plugin.omt.ManageOMTPackage.addZipDir(ManageOMTPackage.java:758) 
93932: Error:   at net.briac.omegat.plugin.omt.ManageOMTPackage.createOmt(ManageOMTPackage.java:659) 
93932: Error:   at net.briac.omegat.plugin.omt.ManageOMTPackage$3.doInBackground(ManageOMTPackage.java:452) 
93932: Error:   at net.briac.omegat.plugin.omt.ManageOMTPackage$3.doInBackground(ManageOMTPackage.java:428) 
93932: Error:   at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304) 
93932: Error:   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) 
93932: Error:   at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343) 
93932: Error:   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) 
93932: Error:   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) 
93932: Error:   at java.base/java.lang.Thread.run(Thread.java:829) 
93932: Error: Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils 
93932: Error:   at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476) 
93932: Error:   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589) 
93932: Error:   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) 
93932: Error:   ... 12 more 
93932: Info: done (87 ms elapsed) 
``` 

It does generate the OMT package, but it's not complete. Unpacking it gives: 

![](https://imgur.com/jmbm6ss.png)

**Comment by msoutopico** [comment]
@briacp I have just realized that this is the same issue I had reported [two issues ago](https://github.com/briacp/plugin-omt-package/issues/11).

**Comment by briacp** [comment]
Yes, when using OmegaT 5.7.x, you must use the 1.7.1 version of the plugin (which is functionnally the same as the 1.8.0 or 1.8.1)

**Comment by msoutopico** [comment]
I thought that version 1.8.0 of the plugin was bound to vesion 6.x of OmegaT. Understood, we'll keep using the previous plugin version with 5.7.2. Thanks!
